/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetApiExternal200Response struct {

	Pong *interface{} `json:"pong,omitempty"`
}

// AssertGetApiExternal200ResponseRequired checks if the required fields are not zero-ed
func AssertGetApiExternal200ResponseRequired(obj GetApiExternal200Response) error {
	return nil
}

// AssertRecurseGetApiExternal200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetApiExternal200Response (e.g. [][]GetApiExternal200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetApiExternal200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetApiExternal200Response, ok := obj.(GetApiExternal200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetApiExternal200ResponseRequired(aGetApiExternal200Response)
	})
}
