openapi: 3.0.0
info:
  description: OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster
    2023
  title: cloudwpss23-openapi-cyan
  version: "1.0"
servers:
- url: http://localhost:3000
- description: ""
  url: https://api.cloudwp.anwski.de
security:
- bearer: []
paths:
  /v1/Buckets:
    get:
      operationId: get-v1-Buckets
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Bucket'
                type: array
          description: OK
      summary: Your GET endpoint
      tags: []
    options:
      operationId: options-v1-Buckets
      responses:
        "200":
          description: OK
      summary: ""
  /v1/Bucket/{BucketName}:
    delete:
      operationId: delete-v1-Bucket-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: ""
    get:
      operationId: get-v1-Bucket-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BucketInfo'
          description: OK
        "404":
          description: Not Found
      summary: Your GET endpoint
      tags: []
    options:
      operationId: options-v1-Bucket-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: ""
    patch:
      description: Set permissions of bucket
      operationId: patch-v1-Bucket-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Permission'
              type: array
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
      summary: ""
    post:
      operationId: post-v1-Bucket-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post_v1_Bucket_name_request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BucketInfo'
          description: OK
        "400":
          description: Bad Request
      summary: ""
  /v1/Bucket/{BucketName}/Files:
    get:
      operationId: get-v1-Files
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/FileInfo'
                type: array
          description: OK
      summary: Your GET endpoint
      tags: []
    options:
      operationId: options-v1-Files
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: ""
  /v1/Bucket/{BucketName}/File/{FileName}:
    delete:
      description: ""
      operationId: delete-v1-File-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: FileName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: ""
    get:
      operationId: get-v1-File-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: FileName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: binary
                type: string
          description: OK
      summary: Your GET endpoint
      tags: []
    options:
      operationId: options-v1-File-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: FileName
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK
      summary: ""
    put:
      operationId: put-v1-File-name
      parameters:
      - explode: false
        in: path
        name: BucketName
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: FileName
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/put_v1_File_name_request'
      responses:
        "200":
          description: OK
      summary: ""
components:
  parameters:
    FileName:
      explode: false
      in: path
      name: FileName
      required: true
      schema:
        type: string
      style: simple
    BucketName:
      explode: false
      in: path
      name: BucketName
      required: true
      schema:
        type: string
      style: simple
  responses: {}
  schemas:
    FileInfo:
      example:
        file:
          name: name
        size: 0
        lastmod: 2000-01-23T04:56:07.000+00:00
      properties:
        file:
          $ref: '#/components/schemas/File'
        size:
          format: int64
          type: integer
        lastmod:
          format: date-time
          type: string
      title: FileInfo
      type: object
      x-stoplight:
        id: 1li8v06fqrcaw
    Bucket:
      example:
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
      title: Bucket
      type: object
      x-stoplight:
        id: 9lwm9t990q1pi
    File:
      example:
        name: name
      properties:
        name:
          type: string
      title: File
      type: object
      x-stoplight:
        id: fqbwtfl7ge8hn
    BucketInfo:
      example:
        owner: owner
        createdAt: 2000-01-23T04:56:07.000+00:00
      properties:
        owner:
          type: string
        createdAt:
          format: date-time
          type: string
      title: BucketInfo
      type: object
      x-stoplight:
        id: mu89lqnnjub82
    Permission:
      example:
        owner: owner
        operations:
        - operations
        - operations
      properties:
        owner:
          type: string
        operations:
          items:
            type: string
          type: array
      title: Permission
      type: object
      x-stoplight:
        id: upycz0qn2bd1j
    post_v1_Bucket_name_request:
      properties:
        name:
          type: string
      type: object
    put_v1_File_name_request:
      properties:
        data:
          format: binary
          type: string
      type: object
  securitySchemes:
    bearer:
      description: ""
      flows:
        authorizationCode:
          authorizationUrl: ""
          refreshUrl: ""
          scopes: {}
          tokenUrl: ""
      type: oauth2
x-stoplight:
  id: l2iyn7fvt7fmd
