/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// DeleteV1BucketName - 
func (s *DefaultApiService) DeleteV1BucketName(ctx context.Context, bucketName string) (ImplResponse, error) {
	// TODO - update DeleteV1BucketName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteV1BucketName method not implemented")
}

// DeleteV1FileName - 
func (s *DefaultApiService) DeleteV1FileName(ctx context.Context, bucketName string, fileName string) (ImplResponse, error) {
	// TODO - update DeleteV1FileName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteV1FileName method not implemented")
}

// GetV1BucketName - Your GET endpoint
func (s *DefaultApiService) GetV1BucketName(ctx context.Context, bucketName string) (ImplResponse, error) {
	// TODO - update GetV1BucketName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BucketInfo{}) or use other options such as http.Ok ...
	//return Response(200, BucketInfo{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetV1BucketName method not implemented")
}

// GetV1Buckets - Your GET endpoint
func (s *DefaultApiService) GetV1Buckets(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetV1Buckets with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Bucket{}) or use other options such as http.Ok ...
	//return Response(200, []Bucket{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetV1Buckets method not implemented")
}

// GetV1FileName - Your GET endpoint
func (s *DefaultApiService) GetV1FileName(ctx context.Context, bucketName string, fileName string) (ImplResponse, error) {
	// TODO - update GetV1FileName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, *os.File{}) or use other options such as http.Ok ...
	//return Response(200, *os.File{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetV1FileName method not implemented")
}

// GetV1Files - Your GET endpoint
func (s *DefaultApiService) GetV1Files(ctx context.Context, bucketName string) (ImplResponse, error) {
	// TODO - update GetV1Files with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []FileInfo{}) or use other options such as http.Ok ...
	//return Response(200, []FileInfo{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetV1Files method not implemented")
}

// OptionsV1BucketName - 
func (s *DefaultApiService) OptionsV1BucketName(ctx context.Context, bucketName string) (ImplResponse, error) {
	// TODO - update OptionsV1BucketName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsV1BucketName method not implemented")
}

// OptionsV1Buckets - 
func (s *DefaultApiService) OptionsV1Buckets(ctx context.Context) (ImplResponse, error) {
	// TODO - update OptionsV1Buckets with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsV1Buckets method not implemented")
}

// OptionsV1FileName - 
func (s *DefaultApiService) OptionsV1FileName(ctx context.Context, bucketName string, fileName string) (ImplResponse, error) {
	// TODO - update OptionsV1FileName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsV1FileName method not implemented")
}

// OptionsV1Files - 
func (s *DefaultApiService) OptionsV1Files(ctx context.Context, bucketName string) (ImplResponse, error) {
	// TODO - update OptionsV1Files with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("OptionsV1Files method not implemented")
}

// PatchV1BucketName - 
func (s *DefaultApiService) PatchV1BucketName(ctx context.Context, bucketName string, permission []Permission) (ImplResponse, error) {
	// TODO - update PatchV1BucketName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PatchV1BucketName method not implemented")
}

// PostV1BucketName - 
func (s *DefaultApiService) PostV1BucketName(ctx context.Context, bucketName string, postV1BucketNameRequest PostV1BucketNameRequest) (ImplResponse, error) {
	// TODO - update PostV1BucketName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, BucketInfo{}) or use other options such as http.Ok ...
	//return Response(200, BucketInfo{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostV1BucketName method not implemented")
}

// PutV1FileName - 
func (s *DefaultApiService) PutV1FileName(ctx context.Context, bucketName string, fileName string, data *os.File) (ImplResponse, error) {
	// TODO - update PutV1FileName with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PutV1FileName method not implemented")
}
