/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type FileInfo struct {

	File File `json:"file,omitempty"`

	Size int64 `json:"size,omitempty"`

	Lastmod time.Time `json:"lastmod,omitempty"`
}

// AssertFileInfoRequired checks if the required fields are not zero-ed
func AssertFileInfoRequired(obj FileInfo) error {
	if err := AssertFileRequired(obj.File); err != nil {
		return err
	}
	return nil
}

// AssertRecurseFileInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FileInfo (e.g. [][]FileInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFileInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFileInfo, ok := obj.(FileInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFileInfoRequired(aFileInfo)
	})
}
