/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostV1BucketNameRequest struct {

	Name string `json:"name,omitempty"`
}

// AssertPostV1BucketNameRequestRequired checks if the required fields are not zero-ed
func AssertPostV1BucketNameRequestRequired(obj PostV1BucketNameRequest) error {
	return nil
}

// AssertRecursePostV1BucketNameRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PostV1BucketNameRequest (e.g. [][]PostV1BucketNameRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePostV1BucketNameRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPostV1BucketNameRequest, ok := obj.(PostV1BucketNameRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPostV1BucketNameRequestRequired(aPostV1BucketNameRequest)
	})
}
