/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type BucketInfo struct {

	Owner string `json:"owner,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}

// AssertBucketInfoRequired checks if the required fields are not zero-ed
func AssertBucketInfoRequired(obj BucketInfo) error {
	return nil
}

// AssertRecurseBucketInfoRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BucketInfo (e.g. [][]BucketInfo), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBucketInfoRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBucketInfo, ok := obj.(BucketInfo)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBucketInfoRequired(aBucketInfo)
	})
}
