/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Bucket struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertBucketRequired checks if the required fields are not zero-ed
func AssertBucketRequired(obj Bucket) error {
	return nil
}

// AssertRecurseBucketRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Bucket (e.g. [][]Bucket), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBucketRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBucket, ok := obj.(Bucket)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBucketRequired(aBucket)
	})
}
