/*
 * cloudwpss23-openapi-cyan
 *
 * OpenAPI Reference für das CloudWP der HAW Hamburg für das SommerSemster 2023
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type File struct {

	Name string `json:"name,omitempty"`
}

// AssertFileRequired checks if the required fields are not zero-ed
func AssertFileRequired(obj File) error {
	return nil
}

// AssertRecurseFileRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of File (e.g. [][]File), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFileRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFile, ok := obj.(File)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFileRequired(aFile)
	})
}
